{"uuid": "5ea06e37-0269-447a-9e41-5e71e13b6b25", "children": ["d0c6e07d-ffef-4405-b190-0d5b5df020a3"], "befores": [{"name": "driver", "status": "passed", "start": 1750126138315, "stop": 1750126230117}], "afters": [{"name": "driver::0", "status": "broken", "statusDetails": {"message": "KeyboardInterrupt\n", "trace": "  File \"C:\\Users\\issuser\\PycharmProjects\\pythonProject1\\venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 231, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\issuser\\PycharmProjects\\pythonProject1\\venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 907, in _teardown_yield_fixture\n    next(it)\n    ~~~~^^^^\n  File \"C:\\Users\\issuser\\ci-pytest-demo\\conftest.py\", line 26, in driver\n    driver.quit()\n    ~~~~~~~~~~~^^\n  File \"C:\\Users\\issuser\\PycharmProjects\\pythonProject1\\venv\\Lib\\site-packages\\selenium\\webdriver\\chromium\\webdriver.py\", line 193, in quit\n    self.service.stop()\n    ~~~~~~~~~~~~~~~~~^^\n  File \"C:\\Users\\issuser\\PycharmProjects\\pythonProject1\\venv\\Lib\\site-packages\\selenium\\webdriver\\common\\service.py\", line 152, in stop\n    self.send_remote_shutdown_command()\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File \"C:\\Users\\issuser\\PycharmProjects\\pythonProject1\\venv\\Lib\\site-packages\\selenium\\webdriver\\common\\service.py\", line 137, in send_remote_shutdown_command\n    if not self.is_connectable():\n           ~~~~~~~~~~~~~~~~~~~^^\n  File \"C:\\Users\\issuser\\PycharmProjects\\pythonProject1\\venv\\Lib\\site-packages\\selenium\\webdriver\\common\\service.py\", line 126, in is_connectable\n    return utils.is_connectable(self.port)\n           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^\n  File \"C:\\Users\\issuser\\PycharmProjects\\pythonProject1\\venv\\Lib\\site-packages\\selenium\\webdriver\\common\\utils.py\", line 101, in is_connectable\n    socket_ = socket.create_connection((host, port), 1)\n  File \"C:\\Users\\issuser\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\socket.py\", line 856, in create_connection\n    exceptions.clear()  # raise only the last error\n    ~~~~~~~~~~~~~~~~^^\n"}, "start": 1750126243449, "stop": 1750126244615}], "start": 1750126138315, "stop": 1750126244615}